config/routes.rb
Rails.application.routes.draw do
 

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#hom'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#aboout'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def hom 
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def aboout
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

    def fullname(lastname='')
    
    end


    class Full

        attr_accessor :name , :email
        def initialize(attributes)
          @name = attributes[:name]
          @email = attributes[:email]
        end

        def formated
            "#{@name}<#{@email}>"
        end 
    end

end

app/views/static_pages/aboout.html.erb
<h1>StaticPages#aboout</h1>
<p>Find me in app/views/static_pages/aboout.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/hom.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
     <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">

  <h1>WELCOM TO THE CROSS</h1>

  <h2>
    If you signup then 
    <%= link_to "click below" , signup_path %>
  </h2>

  <%= link_to "Sign up now!!", signup_path , class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("logos/logo.jpg", alt: "Rails logo"),
            root_path%>

            <% end %>